"use client";
import { FormEvent, ReactNode, useEffect, useState } from "react";
import { Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from "lucide-react";

export default function AuthGate({children}:{children:ReactNode}){
  const [status,setStatus]=useState<"checking"|"guest"|"ready">("checking"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[show,setShow]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[firstAccess,setFirstAccess]=useState(false);
  useEffect(()=>{fetch("/api/auth/session").then(r=>setStatus(r.ok?"ready":"guest")).catch(()=>setStatus("guest"))},[]);
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setMessage("");const endpoint=firstAccess?"/api/auth/bootstrap":"/api/auth/login",response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})}),data=await response.json().catch(()=>({}));setBusy(false);if(response.ok){if(firstAccess){setMessage(data.message);setFirstAccess(false)}else location.reload()}else setMessage(data.error||"Não foi possível acessar.")};
  if(status==="checking")return <div className="auth-loading"><div className="auth-spinner"/><span>Preparando ambiente seguro…</span></div>;
  if(status==="ready")return <>{children}</>;
  return <main className="auth-page"><section className="auth-brand"><div className="auth-logo">P</div><div className="auth-brand-copy"><small>PARSECON CONTABILIDADE</small><h1>Decisões de preço com clareza e segurança.</h1><p>Uma plataforma dedicada à formação de custos, simulações comerciais e análise de rentabilidade.</p></div><div className="auth-trust"><ShieldCheck/><div><b>Ambiente protegido</b><span>Dados e documentos separados por empresa.</span></div></div></section><section className="auth-panel"><div className="auth-card"><span className="auth-kicker">SISTEMA DE CUSTOS</span><h2>{firstAccess?"Criar acesso administrador":"Acesse sua conta"}</h2><p>{firstAccess?"Use o e-mail autorizado da Parsecon para ativar o primeiro administrador.":"Entre com seu e-mail e senha para continuar."}</p><form onSubmit={submit}><label>E-mail<div><Mail/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="seuemail@empresa.com.br" required/></div></label><label>Senha<div><LockKeyhole/><input type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mínimo de 8 caracteres" minLength={8} required/><button type="button" onClick={()=>setShow(!show)} aria-label={show?"Ocultar senha":"Mostrar senha"}>{show?<EyeOff/>:<Eye/>}</button></div></label>{message&&<div className="auth-message">{message}</div>}<button className="auth-submit" disabled={busy}>{busy?"Aguarde…":firstAccess?"Criar primeiro acesso":"Entrar no sistema"}</button></form><button className="auth-first" onClick={()=>{setFirstAccess(!firstAccess);setMessage("")}}>{firstAccess?"Voltar ao login":"Primeiro acesso do administrador"}</button><footer>Precisa de ajuda? <a href="mailto:contato@parsecon.com.br">contato@parsecon.com.br</a></footer></div></section></main>;
}
