"use client";

import { useEffect, useState } from "react";
import { saveDurableValue, useDurableState } from "./use-durable-state";
import { decimal, money, percent } from "./display-format";

type Product={codigo:string|number;nome:string;custo:number;precoCalculado:number;precoPraticado:number;pis:number;cofins:number;irCs:number;icms:number;frete:number;comissao:number;verbas?:number;ggf?:number;despesas?:number;lucroMeta?:number;inadimplencia:number;monophase?:boolean;st?:boolean;simplesIcms?:boolean};
const destinationStates=[["AC","Acre"],["AL","Alagoas"],["AP","Amapá"],["AM","Amazonas"],["BA","Bahia"],["CE","Ceará"],["DF","Distrito Federal"],["ES","Espírito Santo"],["GO","Goiás"],["MA","Maranhão"],["MT","Mato Grosso"],["MS","Mato Grosso do Sul"],["MG","Minas Gerais"],["PA","Pará"],["PB","Paraíba"],["PR","Paraná"],["PE","Pernambuco"],["PI","Piauí"],["RJ","Rio de Janeiro"],["RN","Rio Grande do Norte"],["RS","Rio Grande do Sul"],["RO","Rondônia"],["RR","Roraima"],["SC","Santa Catarina"],["SP","São Paulo"],["SE","Sergipe"],["TO","Tocantins"]] as const;
const defaultIcmsRates:Record<string,number>=Object.fromEntries(destinationStates.map(([uf])=>[uf,["ES","MG","PR","PE","RJ","RS","SC","SP"].includes(uf)?12:7]));
const asPercent=(value:number|undefined,fallback:number)=>{const rate=value??fallback;return Math.abs(rate)<=1?rate*100:rate};
const pisCofinsPercent=(product:Product|undefined)=>product?.monophase?0:asPercent(product?.pis,.0065)+asPercent(product?.cofins,.03);

function DecimalInput({value,onChange,onEdited,disabled=false}:{value:number;onChange:(value:number)=>void;onEdited?:()=>void;disabled?:boolean}){
  const [editing,setEditing]=useState(false),[draft,setDraft]=useState("");
  return <input disabled={disabled} inputMode="decimal" value={editing?draft:decimal(value)} onFocus={()=>{setEditing(true);setDraft(String(value).replace(".",","))}} onChange={event=>{setDraft(event.target.value);const parsed=Number(event.target.value.replace(",","."));if(Number.isFinite(parsed)){onChange(parsed);onEdited?.()}}} onBlur={()=>setEditing(false)}/>;
}

function ResultCard({tone,label,price,cost,items,state,commercial,tablePrice,onApply,onSave}:{tone:"blue"|"green"|"red";label:string;price:number;cost:number;items:{label:string;rate:number;color:string}[];state:string;commercial?:boolean;tablePrice?:number;onApply?:()=>void;onSave?:()=>void}){
  const ggfRate=items.find(item=>item.label==="GGF industrial")?.rate||0;
  const grossMargin=price-cost-price*ggfRate/100,margin=price?grossMargin/price*100:0,profit=items.find(item=>item.label==="Lucro real")?.rate||0,result=price*profit/100;
  const positive=result>=0;
  return <article className={`price-sim-result ${tone}`}><header><small>{label}</small><b>{money(price)}</b><span>por unidade · cenário {state}</span></header><div className="price-sim-summary"><p><span>Margem bruta</span><b>{money(grossMargin)}</b><small>{percent(margin)} · preço menos custo e GGF</small></p><p><span>Resultado final</span><b>{money(result)}</b><small>{positive?"Lucro":"Prejuízo"} · {percent(profit)}</small></p></div><div className="price-composition"><div><span>Composição do preço {commercial?"praticado":"calculado"}</span><b>100%</b></div><i>{items.map(item=><span key={item.label} style={{width:`${Math.max(2,Math.abs(item.rate))}%`,background:item.color}}/>)}</i>{items.map(item=><p key={item.label}><span><em style={{background:item.color}}/>{item.label}</span><b>{percent(item.rate)} · {money(price*item.rate/100)}</b></p>)}</div>{commercial?<div className={`commercial-profit ${positive?"":"loss"}`}><span>{positive?"LUCRO APURADO":"PREJUÍZO APURADO"}</span><b>{money(result)}</b></div>:<><div className="commercial-price"><span>Preço praticado atual na tabela — {state}</span><b>{money(tablePrice||0)}</b></div><div className="price-card-actions"><button onClick={onSave}>Salvar cenário</button><button onClick={onApply}>Aplicar à tabela</button></div></>}</article>;
}

export default function PriceSimulator({products}:{products:Product[]}){
  const initial=Math.max(0,products.findIndex(product=>String(product.codigo)==="871")),initialProduct=products[initial]||products[0],[index,setIndex]=useState(initial),[state,setState]=useState("RS"),[cost,setCost]=useState(initialProduct?.custo??0),[icms,setIcms]=useState(12),[pisCofins,setPisCofins]=useState(3.65),[ircs,setIrcs]=useState(2.28),[ggf,setGgf]=useState(16.16),[admin,setAdmin]=useState(20),[freight,setFreight]=useState(8),[commission,setCommission]=useState(1),[allowance,setAllowance]=useState(0),[defaultLoss,setDefaultLoss]=useState(.05),[profit,setProfit]=useState(6),[edited,setEdited]=useState(false),[applied,setApplied]=useState(false);
  const [stateFreights]=useDurableState<Record<string,number>>("state-freights-v1",Object.fromEntries(destinationStates.map(([uf])=>[uf,8])));
  const [activeRates]=useDurableState<{ggf:number;admin:number;date:string}>("active-ggf-parameters-v1",{ggf:16.16,admin:20,date:"2026-08-01"});
  const [taxSettings]=useDurableState<{rates?:Record<string,number>}>("tax-settings",{rates:defaultIcmsRates});
  const commercialKey=`commercial-prices-${state}`,[commercialPrices,setCommercialPrices]=useDurableState<Record<string,number>>(commercialKey,{});
  const commercialDatesKey=`commercial-dates-${state}`,[commercialDates,setCommercialDates]=useDurableState<Record<string,string>>(commercialDatesKey,{});
  useEffect(()=>{const selected=products[index]||products[0];setFreight(stateFreights[state]??0);setIcms(selected?.st||selected?.simplesIcms===false?0:(taxSettings.rates?.[state]??defaultIcmsRates[state]??0));setEdited(true)},[state,stateFreights,taxSettings,index,products]);
  useEffect(()=>{const next=products[index]||products[0];setCost(next?.custo??0);setPisCofins(pisCofinsPercent(next));setIrcs(asPercent(next?.irCs,.0228));setCommission(asPercent(next?.comissao,.01));setAllowance(asPercent(next?.verbas,0));setDefaultLoss(asPercent(next?.inadimplencia,.0005));setProfit(asPercent(next?.lucroMeta,.06));setGgf(next?.tipo==="IND"?asPercent(next?.ggf,activeRates.ggf/100):0);setAdmin(asPercent(next?.despesas,activeRates.admin/100));setEdited(false)},[index,products,activeRates]);
  const product=products[index]||products[0],commercialRowId=`${product?.codigo}-${index}`,totalRates=icms+pisCofins+ircs+ggf+admin+freight+commission+allowance+defaultLoss+profit,formulaPrice=1-totalRates/100>0?cost/(1-totalRates/100):0,calculated=formulaPrice,practiced=commercialPrices[commercialRowId]??product?.precoPraticado??0,realProfit=practiced?(practiced-cost-practiced*(totalRates-profit)/100)/practiced*100:0;
  const field=(label:string,value:number,setter:(value:number)=>void,locked=false)=><label><span>{label}</span><div><DecimalInput disabled={locked} value={value} onChange={setter} onEdited={()=>setEdited(true)}/><b>%</b></div></label>;
  const chooseProduct=(nextIndex:number)=>{const next=products[nextIndex]||products[0];setIndex(nextIndex);setCost(next?.custo??0);setEdited(true)};
  const common=[{label:"Custo do produto",rate:calculated?cost/calculated*100:0,color:"#0e5e8b"},{label:"Tributos",rate:icms+pisCofins+ircs,color:"#e8a229"},{label:"Despesas administrativas",rate:admin,color:"#25a7b9"},{label:"GGF industrial",rate:ggf,color:"#7061b6"},{label:"Comissão",rate:commission,color:"#86bddd"},{label:"Frete de entrega",rate:freight,color:"#62b2db"},{label:"Verbas comerciais",rate:allowance,color:"#4f7daa"},{label:"Inadimplência",rate:defaultLoss,color:"#8a6f9e"}];
  const practicedItems=[{label:"Custo do produto",rate:practiced?cost/practiced*100:0,color:"#0e5e8b"},...common.slice(1),{label:"Lucro real",rate:realProfit,color:realProfit<0?"#b42318":"#153d5c"}];
  const saveScenario=()=>saveDurableValue(`price-scenario-${product.codigo}-${state}`,{state,cost,icms,pisCofins,ircs,ggf,admin,freight,commission,allowance,defaultLoss,profit,calculated,updatedAt:new Date().toISOString()});
  const applyToCommercialTable=async()=>{const nextPrices={...commercialPrices,[commercialRowId]:calculated},nextDates={...commercialDates,[commercialRowId]:new Date().toISOString().slice(0,10)};setCommercialPrices(nextPrices);setCommercialDates(nextDates);const ok=(await saveDurableValue(commercialKey,nextPrices))&&(await saveDurableValue(commercialDatesKey,nextDates));if(ok){setApplied(true);setTimeout(()=>setApplied(false),1800)}};
  return <div className="price-simulator-page"><section className="price-rule"><span>✓</span><div><b>Taxas carregadas do cadastro do produto</b><p>Ao selecionar um produto, comissão, verbas, inadimplência, lucro e demais taxas são carregadas automaticamente. Alterações feitas abaixo valem para a simulação atual.</p></div><button>Revisar parâmetros</button></section><div className="price-simulator-grid"><section className="price-sim-form"><div className="price-product-search single-selector"><small>PRODUTO</small><select value={index} onChange={e=>chooseProduct(Number(e.target.value))}>{products.map((item,i)=><option value={i} key={`${item.codigo}-${i}`}>{item.codigo} — {item.nome}</option>)}</select></div><div className="price-state single"><label>Estado de destino<select value={state} onChange={e=>setState(e.target.value)}>{destinationStates.map(([uf,name])=><option key={uf} value={uf}>{uf} — {name}</option>)}</select><small>ICMS aplicado automaticamente: <b>{percent(icms)}</b></small></label></div><p className="price-fields-title">Custo e formação do preço <span>Percentuais sobre a venda</span></p><label className="price-cost">Custo líquido do produto<div><span>R$</span><DecimalInput value={cost} onChange={setCost} onEdited={()=>setEdited(true)}/></div></label><div className="price-fields">{field("Tributos",icms+pisCofins+ircs,value=>setIcms(Math.max(0,value-pisCofins-ircs)),true)}{field("Comissão",commission,setCommission)}{field(`Frete para ${state}`,freight,setFreight)}{field("Verbas comerciais",allowance,setAllowance)}{field("Inadimplência",defaultLoss,setDefaultLoss)}{field("Despesas administrativas",admin,setAdmin)}{field("GGF industrial",ggf,setGgf)}{field("Lucro desejado",profit,setProfit)}</div><details><summary>Ver ficha técnica e composição do custo</summary><p>O custo líquido está vinculado à ficha técnica do produto e à embalagem composta.</p></details></section><aside className="price-results"><ResultCard tone="blue" label="PREÇO CALCULADO — SIMULAÇÃO ATUAL" price={calculated} cost={cost} state={state} tablePrice={practiced} items={[...common,{label:"Lucro real",rate:profit,color:"#153d5c"}]} onSave={saveScenario} onApply={applyToCommercialTable}/><ResultCard tone={realProfit<0?"red":"green"} label="PREÇO PRATICADO — TABELA COMERCIAL" price={practiced} cost={cost} state={state} commercial items={practicedItems}/><section className="price-comparison"><small>COMPARATIVO PREÇO × PREÇO</small><p><span>Diferença em reais</span><b>{money(practiced-calculated)}</b></p><p><span>Diferença em percentual</span><b>{percent(calculated?(practiced/calculated-1)*100:0)}</b></p><p><span>Preço sugerido aplicado à tabela</span><b>{applied?"Aplicado e salvo":"Não aplicado"}</b></p></section></aside></div></div>;
}
